import bcrypt from 'bcryptjs';

const data = {
  users:[
    {
      name:'David',
      email:'admin@melasuda.com',
      password: bcrypt.hashSync('12345', 8),
      isAdmin: true,
    },
    {
      name:'John',
      email:'user@melasuda.com',
      password: bcrypt.hashSync('12345', 8),
      isAdmin: false,
    },
  ],
    products: [
      {
        name: 'Be',
        artist: 'Common',
        category: 'Hip Hop',
        image: '/images/01-common-be.jpeg',
        price: 30,
        countInStock: 10,
        label: 'Gefeen',
        rating: 4.5,
        numReviews: 10,
        description: 'New Unselled',
      },
      {
        name: 'Dangerous',
        artist: 'Michael Jackson',
        category: 'Pop',
        image: '/images/02-michaelj-dangerous.jpg',
        price: 25,
        countInStock: 7,
        label: 'Michael Label',
        rating: 5,
        numReviews: 20,
        description: 'New Unselled',
      },
      {
        name: 'Misseucation of Lauryn Hill',
        artist: 'Lauryn Hill',
        category: 'Hip Hop',
        image: '/images/03-miseducation-lauryn.jpeg',
        price: 20,
        countInStock: 1,
        label: 'Gefeen',
        rating: 4,
        numReviews: 6,
        description: 'New Unselled',
      },
      {
        name: 'Queen',
        artist: 'Queen',
        category: 'Rock',
        image: '/images/04-queen-queen.png',
        price: 31,
        countInStock: 3,
        label: 'Gefeen',
        rating: 5,
        numReviews: 13,
        description: 'New Unselled',
      },
      {
        name: 'The Bends',
        artist: 'Radiohead',
        category: 'Rock',
        image: '/images/05-radiohead-thebends.png',
        price: 35,
        countInStock: 0,
        label: 'Gefeen',
        rating: 5,
        numReviews: 15,
        description: 'New Unselled',
      },
      {
        name: 'Californication',
        artist: 'Red Hot Chilli Peppers',
        category: 'Rock',
        image: '/images/06-redhot-californication.jpg',
        price: 20,
        countInStock: 5,
        label: 'Gefeen',
        rating: 4,
        numReviews: 14,
        description: 'New Unselled',
      },
      {
        name: 'Tha Goodfather',
        artist: 'Snoop Dog',
        category: 'Hip Hop',
        image: '/images/07-snoopdog-thagoodfather.jpg',
        price: 22,
        countInStock: 0,
        label: 'Gefeen',
        rating: 4,
        numReviews: 14,
        description: 'New Unselled',
      },
      {
        name: 'Bjork',
        artist: 'Bjork',
        category: 'World Music',
        image: '/images/08-bjork-bjork.jpg',
        price: 32,
        countInStock: 3,
        label: 'Gefeen',
        rating: 5,
        numReviews: 7,
        description: 'New Unselled',
      },

    ],
  };
  export default data;